# Generated by Django 5.1.2 on 2024-10-27 11:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_id', models.CharField(help_text='Unique identifier for the fund', max_length=50, unique=True)),
                ('fund_name', models.CharField(help_text='Name of the investment fund', max_length=255)),
                ('fund_manager_name', models.CharField(help_text='Name of the fund manager', max_length=255)),
                ('fund_description', models.TextField(help_text='Detailed description of the fund')),
                ('fund_nav', models.DecimalField(decimal_places=2, help_text='Net Asset Value of the fund', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_of_creation', models.DateField(help_text='Date when the fund was created')),
                ('fund_performance', models.DecimalField(decimal_places=2, help_text='Fund performance as a percentage', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
            ],
        ),
    ]
