# Generated by Django 5.1.2 on 2024-10-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentFund',
            new_name='Fund',
        ),
    ]
