# Generated by Django 5.1.2 on 2024-10-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_rename_investmentfund_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='id',
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_id',
            field=models.CharField(help_text='Unique identifier for the fund', max_length=50, primary_key=True, serialize=False),
        ),
    ]
