# Generated by Django 5.1.2 on 2024-10-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_remove_fund_id_alter_fund_fund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_id',
            field=models.CharField(help_text='Unique identifier for the fund', max_length=50, primary_key=True, serialize=False, verbose_name='Fund ID'),
        ),
    ]
